name: Lint

on:
  workflow_dispatch:
  push:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    continue-on-error: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Apply fixes
        run: |
          cargo fix --allow-dirty --verbose

      - name: Lint and format
        run: |
          cargo fmt --all -- --check || cargo fmt --all

      - name: Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Lint"
          git push origin main --force
